Use the right encoding to open files.
rsalmaso/grin3 pull request #4
Opened 2020-12-02 15:00 UTC by Natim

Fixes #3

2020-12-14 20:30 UTC, rsalmaso commented
Hi, thanks.
Could you add an `--encoding`, `-x` option which defaults to `sys.stdout.encoding` and use this value?

2020-12-15 07:56 UTC, Natim commented on grin/main.py
> +            block_main = e.object.decode("latin1")
I don't know how to handle this case to be honest. Is it particular to my setup?

Shall we have that to a list of possible encodings and try each of them until it fails?

2020-12-28 10:23 UTC, rsalmaso requested changes
I'm pretty ok with this. Could you add a test for this new option?

2020-12-28 10:23 UTC, rsalmaso commented on grin/grin.py
> +
```suggestion
```

2020-12-28 10:23 UTC, rsalmaso commented on grin/grin.py
> +        openers = dict(text=partial(codecs.open, encoding=encoding), gzip=gzip.open)
```suggestion
        openers = dict(text=partial(codecs.open, encoding=args.encoding), gzip=gzip.open)
```

2020-12-29 15:53 UTC, Natim commented
> Could you add a test for this new option?

I added tests about encoding management.

2021-01-06 23:59 UTC, rsalmaso commented
Manually merged in https://github.com/rsalmaso/grin3/commit/51fdac178e02a5034f8cafaeeffad6cce340bb9e
Release grin3 2.2.0

2021-01-06 23:59 UTC, closed without merging