Add word-matching (-w) and ASCII (-a) options.
rsalmaso/grin3 pull request #7
Opened 2021-06-10 14:25 UTC by ccazabon

This adds -w/--word-regexp options to only match the pattern surrounded by word boundaries, like the GNU grep options with the same names.

In case you only want to use ASCII definitions of word boundaries (or other character classes like \d \D), it also adds the -a/--ascii option.

The handling of the -a option in `get_regex()` isn't particularly elegant, but it works.

Tests included.

2021-06-22 08:47 UTC, rsalmaso requested changes
Thank for this PR

2021-06-22 08:47 UTC, rsalmaso commented on grin/grin.py
> +    )
If this is true by default, it is not needed (I want to remove redundant options).

2021-06-22 08:47 UTC, rsalmaso commented on grin/grin.py
> +        dest="unicode",
```suggestion
        dest="ascii",
        default=False,
```

2021-06-22 08:47 UTC, rsalmaso commented on grin/grin.py
> +        action="store_false",
```suggestion
        action="store_true",
```

2021-06-22 08:47 UTC, rsalmaso commented on grin/utils.py
> +    if not args.unicode:
```suggestion
    if args.ascii:
```

2021-06-22 08:47 UTC, rsalmaso commented on grin/options.py
> +        self.setdefault("unicode", True)
```suggestion
        self.setdefault("ascii", True)
```

2021-06-22 08:47 UTC, rsalmaso commented on tests/test_grep.py
> +        # -u/--unicode
```suggestion
        # -a/--ascii
```

2021-06-22 08:47 UTC, rsalmaso commented on tests/test_grep.py
> +        # No match when unicode not in effect
```suggestion
        # No match when ascii is in effect
```

2021-06-22 09:21 UTC, rsalmaso commented
Could you split this in two commits? One for `-a` and one for `-w`. Thanks!

2021-06-29 19:10 UTC, ccazabon commented on grin/grin.py
> +    )
By all means, if you want to change it, go ahead.  Some projects want to have turn-on and turn-off options for every feature, even if there is a default to one or the other.

2021-06-29 19:11 UTC, ccazabon commented
Okay, I will do so.  Thanks!

2021-06-30 20:21 UTC, ccazabon commented
I've split it into separate commits for the two options, and made the suggested changes to the ASCII option's code.

2021-06-30 20:49 UTC, rsalmaso commented
Thanks, merged manually and released 2.5.0 https://github.com/rsalmaso/grin3/releases/tag/2.5.0

2021-06-30 20:49 UTC, closed without merging